config/routes.rb
Rails.application.routes.draw do

  root "index#index"

  resources :blog, only: %i[index show], constraints: { id: /[^.]+/ }

  resources :testing_labs, only: %i[index]

  namespace :testing_labs do
    resources :hexa_pdf, only: %i[index] do
      collection do
        get 'generating_pdf'
        get 'generate_pdf'

        get 'editing_pdf'
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
# frozen_string_literal: true

class Blog
  class Post
    attr_accessor :permalink, :title, :published_on, :body_html
    private :permalink=, :title=, :published_on=, :body_html=

    def initialize(permalink:, title:, published_on:, body_html:)
      self.permalink = permalink
      self.title = title
      self.published_on = published_on
      self.body_html = body_html
    end

    def slug
      permalink
    end

    def ==(other)
      slug == other.slug
    end
  end

  class PostLoader
    attr_accessor :path
    private :path=

    def initialize(path:)
      self.path = path
    end

    def post
      Post.new(
        published_on: published_on,
        permalink: permalink,
        title: title,
        body_html: body_html
      )
    end

    def published_on
      Date.parse(path_data[1])
    end

    def permalink
      path_data[2].presence&.strip
    end

    def title
      html_doc.xpath('//h1[1]').text
    end

    def body_html
      html_doc.xpath('//h1[1]/following-sibling::*').to_s
    end

    private

    def path_data
      @path_data ||= File.basename(path).match(/(\d{4}-\d{2}-\d{2})-([^.]+)/)
    end

    def html_content
      @html_content ||= markdown_renderer.render(File.read(path))
    end

    def html_doc
      @html_doc ||= Nokogiri::HTML.parse(html_content)
    end

    def markdown_renderer
      Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
    end
  end

  attr_accessor :root, :cache
  private :root=, :cache=

  def initialize(root:, cache: false)
    self.root = Pathname.new(root)
    self.cache = cache
  end

  def posts
    if cache
      @posts ||= load_posts
    else
      load_posts
    end
  end

  def recent_posts
    posts.select { |post| post.published_on > 2.months.ago }.first(3)
  end

  def find(slug)
    post = posts.find { |p| slug == p.slug }
    return post if post

    raise ActiveRecord::RecordNotFound, "No blog post matching #{slug.inspect} found"
  end

  private

  def load_posts
    posts = []
    Dir[root.join('*.md')].each do |path|
      posts << PostLoader.new(path: path).post
    end
    posts.sort_by(&:title).reverse.sort_by(&:published_on).reverse
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  BLOG = Blog.new(root: Rails.root.join('app', 'blog_posts'), cache: Rails.env.production?)

  def index
    @posts = BLOG.posts
    respond_to do |format|
      format.html
      format.rss
    end
  end

  def show
    @post = BLOG.find(params[:id])
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  BLOG = Blog.new(root: Rails.root.join('app', 'blog_posts'), cache: Rails.env.production?)

  def index
    @posts = BLOG.posts.first(3)
  end
end

app/controllers/testing_labs/application_controller.rb
class TestingLabs::ApplicationController < ApplicationController
  def index; end
end

app/controllers/testing_labs/hexa_pdf_controller.rb
class TestingLabs::HexaPdfController < TestingLabs::ApplicationController
  def generating_pdf; end

  def editing_pdf; end

  def generate_pdf
    doc = HexaPdf::Pdf.new(spoof: true)
    return send_data doc.render, filename: 'example.pdf', type: "application/pdf"
  end

  private

  def pdf_params
    params.require(:pdf).permit(:name)
  end
end

app/controllers/testing_labs_controller.rb
class TestingLabsController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def svg(name)
    file_path = "#{Rails.root}/app/assets/images/#{name}.svg"
    return File.read(file_path).html_safe if File.exists?(file_path)
    '(not found)'
  end
end

app/views/blog/index.html.erb
<%= render MainContainer::Component.new do %>
  <div class="mb-5 border-b border-gray-200">
    <h1>Posts 📖</h1>
  </div>

  <div class="grid grid-cols-1 gap-6 md:grid-cols-3">
    <% @posts.each do |post| %>
      <%= render Card::Component.new(title: post.title, description: l(post.published_on), link: blog_path(post.permalink)) %>
    <% end %>
  </div>
<% end %>

app/views/blog/show.html.erb
<%= render MainContainer::Component.new do %>
  <%= link_to blog_index_path, class: "inline-block bg-gray-100 rounded p-3 my-3 hover:bg-gray-200" do %>
    <i class="fas fa-chevron-left"></i> View all posts
  <% end %>

  <div class="mb-5 pb-5 border-b border-gray-200">
    <h1><%= @post.title %></h1>

    <p class="mb-0 font-semibold"><%= l @post.published_on %></p>
  </div>

  <div class="post my-3 space-y-5">
    <%= @post.body_html.html_safe %>
  </div>
<% end %>

app/views/index/index.html.erb
<!-- Hero Section -->
<%= render MainContainer::Component.new do %>
  <div class="space-y-5 md:space-y-0 md:py-5 md:grid md:grid-cols-2 md:gap-x-4 md:place-content-center">
    <!-- left -->
    <div class="md:grid md:justify-items-start md:grid-cols-1 space-y-3 md:space-y-5">
      <h1>Hi! I'm Ted. 👋 <br>Welcome to my Lab. 🧪</h1>

      <p class="font-semibold md:text-lg lg:text-xl">This is where I <span>tinker with tech</span> and break things. <br>And <em>hopefully</em> learn something along the way.</p>

      <div class="animate-wiggle rounded-lg font-semibold md:text-lg lg:text-xl text-gray-100 bg-purple-500 px-5 py-2 inline-block">Alpha</div>

      <p class="md:text-lg lg:text-xl">It's a little bare here at the moment. <br>This is a new website of mine so consider this the alpha version.</p>
    </div>

    <!-- right -->
    <div class="mt-5 md:mt-0">
      <%= link_to testing_labs_hexa_pdf_index_path do %>
        <div class="w-full h-96 rounded-lg shadow-lg overflow-hidden transition duration-200 ease-in-out transform hover:scale-105">
          <div class="bg-purple-500 h-2/3 overflow-hidden">
            <%= image_tag "hexa_pdf.png" %>
          </div>
          <div class="bg-purple-500 p-5 h-1/3">
            <h2 class="text-gray-100">Generating PDFs using HexaPDF</h2>
            <p class="text-gray-100">A useful tool for many end user applications.</p>
          </div>
        </div>
      <% end %>
    </div>

  </div>
<% end %>

<!-- Feature Section -->
<%= render MainContainer::Component.new(styles: "md:space-y-5 bg-gray-100 shadow-md shadow-inner") do %>
  <div>
    <h2 class="inline-block font-sans text-xl md:text-2xl font-bold mr-3 mb-0">Check out my latest blog posts.</h2>
    <p class="inline-block font-semibold">My little journeys in discovering new technologies.</p>
  </div>
  <div class="grid grid-cols-1 gap-6 md:grid-cols-3">
    <% @posts.each do |post| %>
      <%= render Card::Component.new(title: post.title, description: l(post.published_on), link: blog_path(post.permalink)) %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teds Lab</title>
    <%= favicon_link_tag "favicon.svg" %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
  </head>

  <body>
  <header>
    <nav class="flex flex-wrap items-center shadow-md justify-start py-2 px-5 md:px-10 lg:px-20 xl:px-40">
      <!-- logo -->
      <%= link_to root_path do %>
        <%= inline_svg_tag "logo.svg", class: 'w-auto h-12' %>
      <% end %>
      <!-- hamburger -->
      <div class="flex ml-auto md:hidden">
        <button id="hamburger">
          <i class="toggle block fa-2x fas fa-bars"></i>
          <i class="toggle hidden fa-2x fas fa-times"></i>
        </button>
      </div>
      <!-- links -->
      <div class="toggle hidden md:ml-5 md:flex w-full md:w-auto text-right text-bold mt-5 md:mt-0 border-t-2 border-purple-900 md:border-none">
        <% [
             {link: root_path, text: 'Home'},
             {link: blog_index_path, text: 'Blog'},
             {link: testing_labs_path, text: 'Testing Labs'},
           ].each do |nav_link| %>
          <%= render NavbarLink::Component.new(link: nav_link[:link], text: nav_link[:text]) %>
        <% end %>
      </div>
      <!-- social links -->
      <div class="toggle hidden md:ml-auto md:flex w-full md:w-auto text-right text-bold mt-0">
        <%= render NavbarSocialLink::Component.with_collection(
          [
            {link: 'https://github.com/tedkeep/teds-lab', iconClass: 'fab fa-2x fa-github'},
            {link: 'https://www.linkedin.com/in/tedkeep/', iconClass: 'fab fa-2x fa-linkedin-in'},
          ]) %>
      </div>
    </nav>
  </header>

  <script>
      document.getElementById("hamburger").onclick = function toggleMenu() {
          const navToggle = document.getElementsByClassName("toggle");
          for (let i = 0; i < navToggle.length; i++) {
              navToggle.item(i).classList.toggle("hidden");
          }
      };
  </script>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

  </body>
</html>

app/views/testing_labs/hexa_pdf/editing_pdf.html.erb
<turbo-frame id="content">
  <h1>Editing PDFs</h1>
  <p>To edit PDFs add a PDF attachment below and click the button. It should return an edited version of the PDF you uploaded.</p>

  <p>(This page is yet to be finished. Mainly here to test the multiple pages for each "testing lab" area.)</p>
</turbo-frame>

app/views/testing_labs/hexa_pdf/generating_pdf.html.erb
<turbo-frame id="content">
  <h1>Generating PDFs</h1>
  <p>Click the button below to generate a simple PDF.</p>

  <%= button_to "Generate PDF", generate_pdf_testing_labs_hexa_pdf_index_path, method: :get, "data-turbo": false %>
</turbo-frame>

app/views/testing_labs/hexa_pdf/index.html.erb
<%= render MainContainer::Component.new do %>
  <div class="flex flex-col-reverse md:flex-row gap-10">

    <%= render NavCard::Component.new do |c| %>
      <% c.links([
                   {text: "Generating PDFs", link: generating_pdf_testing_labs_hexa_pdf_index_path},
                   {text: "Editing PDFs", link: editing_pdf_testing_labs_hexa_pdf_index_path},
                 ]) %>
    <% end %>

    <div class="md:flex-grow md:align-center">
      Testing Labs are still in a "pre alpha" state. Early <strong>Early</strong> access.
      <turbo-frame id="content" src="<%= generating_pdf_testing_labs_hexa_pdf_index_path %>">
      </turbo-frame>
    </div>
  </div>
<% end %>

app/views/testing_labs/index.html.erb
<%= render MainContainer::Component.new do %>
  <div class="mb-5 border-b border-gray-200">
    <h1 class="md:inline-block">Testing Labs 🧪</h1>
    <p class="md:inline-block">Interactive labs to play around with different tech</p>
  </div>

  <div class="grid grid-cols-1 gap-6 md:grid-cols-3">
    <% [
         {title: "HexaPDF", description: "Create and edit PDF documents", link: testing_labs_hexa_pdf_index_path}
       ].each do |lab| %>
      <%= render Card::Component.new(lab) %>
    <% end %>
  </div>
<% end %>